# Generated by Django 3.2.6 on 2021-08-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortener_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='custom_short_url',
            field=models.CharField(blank=True, max_length=31, unique=True),
        ),
    ]
