# Generated by Django 3.2.6 on 2021-08-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_shortener_custom_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='long_url',
            field=models.URLField(blank=True, max_length=31, unique=True),
        ),
    ]
