# Generated by Django 3.2.6 on 2021-08-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_alter_shortener_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=31, null=True, unique=True),
        ),
    ]
