# Generated by Django 3.2.6 on 2021-08-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20210818_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='custom_random_short_url',
        ),
        migrations.AddField(
            model_name='shortener',
            name='custom_short_url',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
