# Generated by Django 3.2.6 on 2021-09-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_auto_20210818_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='long_url',
            field=models.URLField(blank=True, max_length=100, unique=True),
        ),
    ]
